ds_params:
  split_params:
    'n_splits': 1
    'test_size': 0.3
    'random_state' : 1
  tgt_variable:
    - 'deposit'  
  xgb_params:
    n_estimators: 80
    learning_rate: 0.1
    gamma: 0
    subsample: 0.75
    colsample_bytree: 1
    max_depth: 5
  lr_params:
  knn_params:
  svc_params:
  nb_params:
    
