ds_params:
  split_params:
    'n_splits': 1
    'test_size': 0.3
    'random_state' : 1
  tgt_variable:
    - 'deposit'  
  model_params:
    model_name: CatBoostClassifier
    scoring_params : ['accuracy','precision','recall','f1','roc_auc']
    refit: roc_auc
    param_distributions:
      depth: [4,5,6,]
      learning_rate: [0.1,0.2,0.3,]
      n_estimators: [100,200,300,]
    random_state: 43

    
